### PR TITLE
Add deprecation warning to site header

### PR DESCRIPTION
**Pull request by line47**
Add deprecation warning to site header

### CODE REVIEW

**Review by bernardwang — APPROVED** [review]
LGTM!

**Review by mliupaeter — COMMENTED** [review]
I just got an update from Jon to remove the line with august time frame. So remove "As of August 2020, this site will no longer be available"

**Comment by line47** [comment]
The copy has been removed, who has the ability to merge this?

**Comment by line47** [comment]
Updated screenshot of changes - thanks @mliupaeter 

image

**Comment by mliupaeter** [comment]
@line47 
There's a content change:
Language changes requested by CSG:

From "This site has been deprecated and is no longer being updated or supported."
To "This website is no longer being updated or supported." 

Once it's made I can merge it with no other approvals.

**Comment by line47** [comment]
@mliupaeter I updated the text here - https://github.com/CMSgov/HealthCare.gov-Styleguide/pull/196/files#diff-822e9cf54ee310f9a7ebd0d16c9ae066R33 

We should be good to merge now 🚀 👍

**Comment by mliupaeter** [comment]
Thanks @line47 Merging now.

**Pull request merged**
